select TEAM.TEAMNAME,coach.VORNAME,coach.NACHNAME,coach.DISPLAYNAME,race.RACENAME,season.SHORTNAME FROM TEAM
inner join COACH coach on coach.ID = TEAM.COACH
inner join ALLOWEDRACE race on race.ID = TEAM.ALLOWEDRACE
inner join SEASON season on season.ID = TEAM.SEASON
order by season.SHORTNAME,TEAM.TEAMNAME;

select BBMATCH.MATCHNUMBER,team1.TEAMNAME,team2.TEAMNAME,BBMATCH.TOUCHDOWNSTEAM1,BBMATCH.TOUCHDOWNSTEAM2,BBMATCH.POINTMODIFICATIONTEAM1,BBMATCH.POINTMODIFICATIONTEAM1,BBMATCH.ISPLAYOFFMATCH,BBMATCH.ISTOURNAMENTMATCH,season.SHORTNAME from BBMATCH
inner join TEAM team1 on team1.ID = BBMATCH.TEAM1
inner join TEAM team2 on team2.ID = BBMATCH.TEAM2
inner join SEASON season on season.ID = BBMATCH.SEASON_ID
Order By season.SHORTNAME, BBMATCH.MATCHNUMBER;