apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: blood-bowl-season-manager
  labels:
    app: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - image: postgres:15
          name: postgresql
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: blood-bowl-season-manager-database
                  key: database
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: blood-bowl-season-manager-database
                  key: user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: blood-bowl-season-manager-database
                  key: password
            - name: PGDATA
              value: "/var/lib/postgresql/data/pgdata"
          ports:
            - containerPort: 5432
              name: postgresql
          volumeMounts:
            - name: postgres-db-volume
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-db-volume
          persistentVolumeClaim:
            claimName: nfs-blood-bowl-season-manager-db-pvc