apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-blood-bowl-season-manager-postgres
  namespace: blood-bowl-season-manager
  labels:
    volume: blood-bowl-season-manager-postgres
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
   - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /volume1/kubernetes-blood-bowl-season-manager
    server: thevoid