apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pv-paypal-blood-bowl-league-manager-certificates-pvc
  namespace: blood-bowl-league-manager
spec:
  selector:
    matchLabels:
      volume: blood-bowl-league-manager-certificates
  accessModes: [ "ReadOnlyMany" ]
  storageClassName: ""
  resources:
    requests:
      storage: 200M