apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-blood-bowl-league-manager-logos-pvc
  namespace: blood-bowl-league-manager
spec:
  selector:
    matchLabels:
      volume: blood-bowl-league-manager-images
  accessModes: [ "ReadWriteMany" ]
  storageClassName: ""
  resources:
    requests:
      storage: 1.Gi