apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: blood-bowl-league-manager
  labels:
    deployment: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: blood-bowl-league-manager
          image: barryallenofearth/blood-bowl-league-manager:36
          env:
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: blood-bowl-league-manager-database
                  key: database
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: blood-bowl-league-manager-database
                  key: user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: blood-bowl-league-manager-database
                  key: password
            - name: DATABASE_URI
              value: postgresql://$(DB_USER):$(DB_PASSWORD)@postgresql:5432/$(DB_NAME)
          resources: { }
          ports:
            - containerPort: 443
              name: https
          volumeMounts:
            - mountPath: /app/blood-bowl-league-manager/data/leagues.csv
              name: data-files
              subPath: leagues.csv
            - mountPath: /app/blood-bowl-league-manager/data/seasons.csv
              name: data-files
              subPath: seasons.csv
            - mountPath: /app/blood-bowl-league-manager/data/races.csv
              name: data-files
              subPath: races.csv
            - mountPath: /app/blood-bowl-league-manager/data/teams_and_coaches.csv
              name: data-files
              subPath: teams_and_coaches.csv
            - mountPath: /app/blood-bowl-league-manager/data/matches.csv
              name: data-files
              subPath: matches.csv
            - mountPath: /app/blood-bowl-league-manager/data/additional_statistics.csv
              name: data-files
              subPath: additional_statistics.csv
            - name: images-volume
              mountPath: /app/blood-bowl-league-manager/server/static/logos
            - name: certificates-volume
              mountPath: /app/blood-bowl-league-manager/certificates
          livenessProbe:
            httpGet:
              path: /health
              port: 443
              scheme: HTTPS
            periodSeconds: 60
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /
              port: 443
              scheme: HTTPS
            periodSeconds: 60
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          startupProbe:
            httpGet:
              path: /
              port: 443
              scheme: HTTPS
            periodSeconds: 30
            timeoutSeconds: 30
            failureThreshold: 3
            successThreshold: 1
      volumes:
        - name: data-files
          configMap:
            name: init-files-blood-bowl-league-manager
        - name: images-volume
          persistentVolumeClaim:
            claimName: nfs-blood-bowl-league-manager-logos-pvc
        - name: certificates-volume
          persistentVolumeClaim:
            claimName: nfs-pv-blood-bowl-league-manager-certificates-pvc