apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blood-bowl
  namespace: blood-bowl-league-manager
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - kubernetes-master.fritz.box
      secretName: ingress-cert
  rules:
  - host: kubernetes-master.fritz.box
    http:
        paths:
          - path: /blood-bowl
            pathType: Prefix
            backend:
              service:
                name: webapp
                port:
                  name: http